# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
      - master
      - 'feature/**'

jobs:
  main:
    name: pytest
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.8, 3.11]
        os: [ ubuntu-latest ]

    steps:
    - name: Check out
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run required services (Fuseki)
      run: |
        make fuseki-create-test-dbs

    - name: Install dependencies
      run: |
        make install

    - name: Test with pytest
      run: |
        make test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: coverage.xml
        flags: unittests
        env_vars: OS,PYTHON
        name: codecov-umbrella
        fail_ci_if_error: true
